name: daily
 
on:
  schedule:
    - cron: '45 3 */2 * *'
    
  workflow_dispatch:

jobs:
  schedule-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: python
        uses: actions/setup-python@v1

      - name: pushshift-api
        run: |
          pip install requests
          python .github/script.py interestingasfuck

      - name: preserve-changes
        run: |
          git config --global user.email "pedro-bot@actions.com"
          git config --global user.name "pedro-bot"
          git add -A
          git commit -m "update"
          git push origin main
