name: daily
 
on:
  schedule:
    - cron: '25 17 */1 * *'
    
  workflow_dispatch:

jobs:
  schedule-push:
    runs-on: ubuntu-latest
    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      R_PASSWORD: ${{ secrets.R_PASSWORD }}
     
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: python
        uses: actions/setup-python@v1

      - name: run script
        run: |
          pip install requests
          python .github/script.py foodporn

      - name: preserve-changes
        run: |
          git config --global user.email "pedro-bot@actions.com"
          git config --global user.name "pedro-bot"
          git add -A
          git commit -m "README auto update"
          git push origin main
